### ISSUE TITLE
Add the flow on how docs get published in the readme file.

### ISSUE THREAD

**Issue by mahebbar** [openebs/openebs-docs#108]

**Comment by sayak119** [comment]
Hi @mahebbar can you please provide more info. Like what to do here. Should I write how Docusaurus works with the openebs or just the process like make a PR -> then the travis integration (what all happens in it) and then updating the site with the PR if it has passed tests and merged.

**Comment by mahebbar** [comment]
@sayak119 the readme here https://github.com/openebs/openebs-docs must include the process from the time you open the doc to edit (based on an issue), go to openebs website folder and use npm start to preview the doc in localhost, submitting PR for review with the DCO sign off > CI integration requires one approval and DCO signoff to be successful > once successful you will be able to merge the PR.
