### ISSUE TITLE
Provide link (anchors) to sub-topics on the docs.openebs.io

### ISSUE THREAD

**Issue by ksatchit** [openebs/openebs-docs#153]
We need to have a tree-view like structure on the sidebar OR have a menu in every major page - consisting of links to the sub-topics. A case in point is : the **storage pool policy** info can be reached by scrolling down in the policies page - we should ideally have a link to reach the intended section : https://docs.openebs.io/docs/storagepolicies.html

**Comment by sagarkrsd** [comment]
@ksatchit Something like this 
![image](https://user-images.githubusercontent.com/31482140/39508311-a4c2872a-4dff-11e8-8cbd-bca361b94be1.png)

**Comment by sagarkrsd** [comment]
The sidebars have been included in the openebs-docs -

![image](https://user-images.githubusercontent.com/31482140/40177161-60b3ba2e-59fb-11e8-9986-ad73123cd894.png)
