### ISSUE TITLE
Update README.md file

### ISSUE THREAD

**Issue by Akash4927** [openebs/openebs-docs#198]
## BUG REPORT

**What happened**:
After following the README to setup openebs-docs on local system, it throws an error
`Error: No sidebar file available to use for version latest. Verify that 'version-latest-sidebars.json' exists`

**What you expected to happen**:
It should start the server.

**How to reproduce it (as minimally and precisely as possible)**:
Clone the repository.
Change directory to openebs-docs/website
Run `npm install docusaurus`
Run `npm start`

Remove `npm install docusaurus` from the README.md file.

**Comment by mahebbar** [comment]
Readme is updated

**Comment by sanshay** [comment]
i am working on it
please assign the same to me
