### ISSUE TITLE
not able to reach at a link provided in docs.

### ISSUE THREAD

**Issue by atulabhi** [openebs/openebs-docs#212]
I want to update my openebs deployment on cluster i was following the openebs docs but when i click on the link provided in step 2 it through **404**.

![image](https://user-images.githubusercontent.com/30014772/40295741-144fc376-5cf8-11e8-8cc4-8d4ce8e8873a.png)

![image](https://user-images.githubusercontent.com/30014772/40295754-2144fdbc-5cf8-11e8-8a95-3e4034c8055b.png)

**Comment by utkarsh2102** [comment]
To: @kmova, @NisantaSahoo, @mahebbar.
How about adding the `tags` link to the documentation?
It'd redirect the viewer to the latest released tags. And then the viewer could update as per their version choice?
If so, I'd like to take up the task.

**Comment by ChandanSagar** [comment]
We have revamped the section. Now it's working. So closing this ticket.
