### ISSUE TITLE
doc: Misplaced headlines in faq

### ISSUE THREAD

**Issue by everflux** [openebs/openebs-docs#280]
In https://docs.openebs.io/docs/next/faq.html the headlines for
"How about performance? How does OpenEBS perform?" and "What changes must be made to the containers on which OpenEBS runs?" are swapped in relation to the paragraph text below.

Sorry that I did not open a PR, but I was unable to find the doc file.

**Comment by mahebbar** [comment]
Modified the FAQ document.
