### ISSUE TITLE
Maintain docs version using json file

### ISSUE THREAD

**Issue by Akash4927** [openebs/openebs-docs#313]
Currently, the version is hardcoded in the docusaurus code. Whenever we release a new version, we need to add it in the code. 
https://github.com/openebs/openebs-docs/blob/80566bf9b4a00bd8ed2cde21fffce9b82c7ec48c/website/node_modules/docusaurus/lib/core/nav/HeaderNav.js#L242

Instead of this, we need to maintain a `version.json` file which will have all the versions and their links. (Similar to [sidebars.json](https://github.com/openebs/openebs-docs/blob/master/website/sidebars.json) file)

Implement logic to fetch version from version.json file and show in the dropdown menu.

Whenever we release a new version, we need to update the `version.json` file.

**Comment by swatisingh45** [comment]
Hey! I would love to take up the issue. Please assign this to me.

**Comment by Akash4927** [comment]
@swatisingh45 Please go ahead

**Comment by swatisingh45** [comment]
Hey! So you want a json version of this version.json, right? Where to do that?

**Comment by Akash4927** [comment]
@swatisingh45 In the website directory, you can find sidebars.json, we can have the version.json in the same directory.

**Comment by Akash4927** [comment]
We do not want only the JSON file, but also the implementation to fetch the version drop-down content using that JSON file.

**Comment by mathagician** [comment]
Hello, if not done I would like to take it up.

**Comment by Akash4927** [comment]
Hi @mathagician, @swatisingh45 didn't respond yet. If you want to pick it up, please go ahead.

**Comment by sudonitesh** [comment]
is someone working on this or I can take it?

**Comment by Akash4927** [comment]
@mathagician are you working on this?

**Comment by sudonitesh** [comment]
@Akash4927  any update?

**Comment by Akash4927** [comment]
@sudonitesh I think you can work on this and don't forget to join **hacktoberfest2018** channel on our [slack workspace](https://openebs-community.slack.com/).

**Comment by Rishabh570** [comment]
@Akash4927 I would like to work on this

**Comment by Akash4927** [comment]
@Rishabh570 Please go ahead.

**Comment by Rishabh570** [comment]
@Akash4927 Okay, so far what I've understood is, we need to write the version in the `versions.json` and then extract its value (through some js method call to `./versions.json`) and use it wherever needed, like in the headerNav...so we don't have to manually change its value from the file, just updating `versions.json` would suffice. Have I made a mistake in understanding this?

**Comment by Rishabh570** [comment]
@Akash4927 I was installing the repo for local development and got stuck while doing `npm start`. This is error message I'm getting...

![screenshot from 2018-10-17 16-59-47](https://user-images.githubusercontent.com/25483260/47083471-4f908500-d22e-11e8-9ad0-19199959108b.png)

**Comment by Akash4927** [comment]
@Rishabh570 Can you please join our hacktoberfest-2018 channel on [slack](https://slack.openebs.io)?

**Comment by Rishabh570** [comment]
Sure, done! I'll ask it there :)
