### ISSUE TITLE
Make the right side menu headings to Bold

### ISSUE THREAD

**Issue by umamukkara** [openebs/openebs-docs#318]
Issue type: Enhancement
Complexity: Easy

Issue description:

https://docs.openebs.io has two menus. The main menu on the LHS and TOC menu on the RHS. We would like to see the headings on the RHS in bold-font.

In the example page:
https://docs.openebs.io/#as-an-application-developer
"As a Kuberntes Operator/Administrator" and "As an application developer" should be made bold

**Comment by aprex** [comment]
Hi, I'd like to help with this

**Comment by umamukkara** [comment]
@aprex thank you so much for the quick PR. I am creating more issues for contributions in this repo. #320 may interest you.

**Comment by arshadkazmi42** [comment]
I think this issue should be closed now. looks like there has been a fix already merged at #319

**Comment by ranjithwingrider** [comment]
Thank you @aprex for making the changes.
