### ISSUE TITLE
Expanding  one heading should compress the other expanded heading

### ISSUE THREAD

**Issue by umamukkara** [openebs/openebs-docs#320]
Issue type: Feature enhancement
Complexity: Easy
Issue description: 
OpenEBS docs site https://docs.openebs.io/ has two menus  - Main menu on the LHS and TOC menu on the RHS.

On the LHS if you click the Red heading "Concepts" the section expands, but the already expanded section "Getting Started" does not compress. We would like to have this fixed.

**Comment by sonumeewa** [comment]
can i work on this one ?

**Comment by Akash4927** [comment]
@sonumeewa Thank you

**Comment by anuragsachdeva28** [comment]
Can I work on this issue?

**Comment by gutsytechster** [comment]
Hey is the issue still open @Akash4927?

**Comment by mathagician** [comment]
This issue is not solved. I would like to take it. Can you please assign to me and provide necessary direction.

**Comment by jainsaarthak** [comment]
Is this issue still open? I would like to work on it.

**Comment by agarwalrounak** [comment]
Hi, I am able to figure out the problem. May I start working on it?

**Comment by ranjithwingrider** [comment]
@qiell Can you give some insights to this problem so that we can assign to one of the interested developer who knows the fix.

**Comment by AmitKumarDas** [comment]
@agarwalrounak you can start working on this
