### ISSUE TITLE
UX / JavaScript - More elegant LHS menu for docs.openebs.io

### ISSUE THREAD

**Issue by umamukkara** [openebs/openebs-docs#322]
Issue type: Feature enhancement
Complexity: Easy
Issue description:
OpenEBS docs site https://docs.openebs.io/ has two menus - Main menu on the LHS and TOC menu on the RHS.

The background color for LHS is white and could look better like shown in the below link.
https://console.bluemix.net/docs/containers/cs_storage_basics.html#kube_concepts

**Comment by arshadkazmi42** [comment]
I can take this up.

**Comment by umamukkara** [comment]
Please post some screenshots and then send a PR. Thanks for working on this @arshadkazmi42

**Comment by Akash4927** [comment]
@arshadkazmi42 I think you should make it full height. 
You can also experiment by changing colors and fonts to make it more attractive and send screenshots.

**Comment by arshadkazmi42** [comment]
Awesome, let me create a PR right away 👍

**Comment by arshadkazmi42** [comment]
@Akash4927 I have created PR against staging branch. Is that fine? Or it needs to be against master branch?

**Comment by Akash4927** [comment]
@arshadkazmi42 Thanks for the PR and it's fine. We'll review it soon. :slightly_smiling_face:
