### ISSUE TITLE
JavaScript: The docs website logo does not appear in the correct size

### ISSUE THREAD

**Issue by umamukkara** [openebs/openebs-docs#323]
Issue type: Bug fix
Complexity: Easy
Issue description:
OpenEBS docs site https://docs.openebs.io/ has a logo on the top left corner. The mule logo and the text in the OpenEBS Docs are created as one image. Because of this, the mule logo is not appearing as one image.

We probably need to split this into two images, One with just the Mule whose height can be more than the other image (OpenEBS Docs). This probably needs changes to JavaScript to support more than one image as part of the header logo or any other solution.

**Comment by OPARA-PROSPER** [comment]
i can work on this

**Comment by OPARA-PROSPER** [comment]
Since you suggested splitting the images into two. How do i get them? Also whats the Js file for the site?

**Comment by Akash4927** [comment]
Hi @OPARA-PROSPER, Thanks for picking up the issue. 

The logo is a header icon whose path is defined in [siteConfig.js](https://github.com/openebs/openebs-docs/blob/33f5c62b264e0faf484e2f7633a47aa425b244e2/website/siteConfig.js#L35). 
You can find the image in [static](https://github.com/openebs/openebs-docs/blob/staging/website/static/img/openebs-logo.svg) directory. 

HeaderIcon implementation is residing in [HeaderNav.js](https://github.com/openebs/openebs-docs/blob/staging/website/node_modules/docusaurus/lib/core/nav/HeaderNav.js#L230) and [feed.js](https://github.com/openebs/openebs-docs/blob/33f5c62b264e0faf484e2f7633a47aa425b244e2/website/node_modules/docusaurus/lib/server/feed.js#L20) files. 

If you have any further query, please let us know.

You can also join **hacktoberfest2018** channel on our [slack workspace](https://openebs-community.slack.com/).

**Comment by OPARA-PROSPER** [comment]
The link prompts me to login instead of registering. Can you please check it out

**Comment by Akash4927** [comment]
@OPARA-PROSPER I've updated the link.

**Comment by Akash4927** [comment]
@OPARA-PROSPER  You can use these images for the header icon.
[OpenEBS logo](https://github.com/openebs/openebs-docs/blob/staging/website/static/img/OpenEBS-logo.svg)
[OpenEBS Docs logo](https://github.com/openebs/openebs-docs/blob/staging/website/static/img/openebs-docs-logo.svg)

**Comment by devshiva619** [comment]
@Akash4927 Hey can I take this one?

**Comment by brute4s99** [comment]
I would like to submit a PR for this issue, @Akash4927 !

**Comment by anuragsachdeva28** [comment]
Is this issue still open?

**Comment by brute4s99** [comment]
I have submitted work on this issue, @anuragsachdeva28

**Comment by ranjithwingrider** [comment]
Hi @brute4s99 . Thank you for making the appropriate changes with OpenEBS logo. PR #368 has been merged.
