### ISSUE TITLE
Typos in openebs-docs/docs/installation.md       

### ISSUE THREAD

**Issue by swetax** [openebs/openebs-docs#354]
There are some typos in openebs-docs/docs/installation.md

**Comment by swetax** [comment]
Solved this in #357 
Please review this .

**Comment by ulshell** [comment]
I would like to work on iit

**Comment by nimesh70** [comment]
i  would like to fix the issue

**Comment by ranjithwingrider** [comment]
Doc has been updated with your changes. Thank you @swetax .
