### ISSUE TITLE
Grammatical error in FAQ.md file

### ISSUE THREAD

**Issue by ManavpreetSingh** [openebs/openebs-docs#399]
There are some grammatical error in FAQ.md file, I  would like to fix them

**Comment by valerianpereira** [comment]
Is this fixed @ManavpreetSingh ?

**Comment by umamukkara** [comment]
@ManavpreetSingh , first of all, sorry for the delay for the response on this and thank you for your interest. The specific errors are not mentioned. Please feel free to fix them.

**Comment by ranjithwingrider** [comment]
Reformatted FAQ. Hence this is closed.
