### ISSUE TITLE
Need a overview section for cStor

### ISSUE THREAD

**Issue by kmova** [openebs/openebs-docs#478]
Creating this issue based on conversation with @davidkarlsen on OpenEBS Slack. 

There are quite a bit of resources and concepts to get the hang of. What I have gathered so far on how cStor works is:
1) disks are found via NDM, and “disk” can actually be a folder, or a block-device
2) disks are collected into pools, and these can actually be “block-disks”, or “folder-disks”, they are called sparse by convention if they use “folder disks” - but really the disk list can be any type disk
3) storageclasses use the pools to allocate underlying storage - like any k8s storageclass.

**Comment by davidkarlsen** [comment]
also:

1) document parameters for the storageclass (for instance, can a default fsType be given for xfs | ext4

2) data-reciliency, I see that storagepools can be mirrored, and this requires two equal disks on each *node* or striped, which is across nodes -  but there is also a concept of replication (default 3?)

**Comment by umamukkara** [comment]
More queries from @davidkarlsen  on the pool replica and types of replication within a given pool replica etc. Explain the cStor pool replica concepts as well.

**Comment by kmova** [comment]
Used the diagrams in the following slide to explain how striped pool works. 
https://docs.google.com/presentation/d/1P6m_mbRTGlU8wpyyp3qVpKOg6kY8_Co8XWj0qke4Shg/edit#slide=id.g4d60598ed0_0_145

**Comment by davidkarlsen** [comment]
Generally I think this looks very good.
Maybe it is worthwhile to elaborate a bit over the resilience with replication vs resilience with mirroring at the node-level?

**Comment by ranjithwingrider** [comment]
updated the doc with new changes 
https://docs.openebs.io/docs/next/cstor.html
