### ISSUE TITLE
How to setup iSCSI on RKE with RancherOS

### ISSUE THREAD

**Issue by kmova** [openebs/openebs-docs#479]
@chtardif tried this and found the following steps work:

1) Install rancheros
2) Install open-iscsi support
  - ros s enable open-iscsi
  - ros s up open-iscsi
      - These two commands will basically bring iscsi binaries + kernel modules to the host, but on a separate system container, as everything runs in containers on RancherOS
3) Install OpenEBS (+ SPC's, SC's, you know the job)
4) Create your PVC and your container, and enjoy the thing !!!

**Comment by prabhatkumarthakur** [comment]
@kmova The above commands were really helpful.

Steps performed by me.
1.Installed Rancher OS -1.4.3
2.Enable Rancher dashboard 2.1.6
3. Created k8s cluster on vsphere with underline os as Rancher OS (1.5.1)
4. Check the status of open-iscsi system service on nodes.
   $sudo ros s list | grep iscsi
The output of the above command is below. 
 disabled open-iscsi
 
5. Check the status of iscs_tcp module.
 $lsmod | grep iscsi 
The above command will give no output. 

6.Enabled open-iscsi system service on nodes using below command.
  $sudo ros s enable open-iscsi
  
7.Started open-iscsi system service on nodes using below command.
   $sudo ros s up open-iscsi
8.Check the status of iscs_tcp module.
  $lsmod | grep iscsi
iscsi_tcp 20480 0
libiscsi_tcp 24576 1 iscsi_tcp
libiscsi 53248 2 libiscsi_tcp,iscsi_tcp
scsi_transport_iscsi 98304 2 libiscsi,iscsi_tcp  

9. Deployed openEBS using helm.
10.Deployed application on OpenEBS .

**Comment by ranjithwingrider** [comment]
This is documented . 
https://docs.openebs.io/docs/next/prerequisites.html#rancher
