### ISSUE TITLE
What are the minimum system requirements to connect OpenEBS clusters to MO?

### ISSUE THREAD

**Issue by kmova** [openebs/openebs-docs#485]
When connecting to MO, there are a set of agent pods that are installed. What should be the minimum CPU/RAM available? Any network requirements to connect to MO?

**Comment by ranjithwingrider** [comment]
System requirements (or resource required)
Installation of MayaOnline agents happen into maya-system namespace. On an average, the agents consume around 500mi node memory and 300-400m node cpu per node.

Users can in general connect any Kubernetes cluster versioned above 1.10.x to MayaOnline and OpenShift versioned above 3.x. 

Users need to authenticate to MayaOnline using their GitHub credentials

Users need to have access to Kubernetes admin context to install MayaOnline agents on Kubernetes.
These details are mentioned in https://docs.openebs.io/docs/next/mayaonline.html
