### ISSUE TITLE
Update StorageClass section 

### ISSUE THREAD

**Issue by ranjithwingrider** [openebs/openebs-docs#490]
This issue is raised by Austin Harris in the community channel.

Some confusion is with the statement made under Setting Up Storage Class On OpenEBS.
Update needed for below statement

> Apply the openebs-operator.yaml file on the Kubernetes cluster using the following command. This creates the maya api-server and OpenEBS components which includes default storage classes.

In the first paragraph under this section, it is mentioning about the OpenEBS installation. So it is not need to provide again about installation method.

**Comment by gr33ngiant112** [comment]
👍 It could be noted above **Note: If you've already installed openebs via Helm or otherwise, skip the following `apply` step, something like that. thank you!

**Comment by ranjithwingrider** [comment]
@gr33ngiant112 This change has been updated in the documentation.  https://docs.openebs.io/docs/next/setupstorageclasses.html. Thank you @gr33ngiant112 
#492
