### ISSUE TITLE
Include information on how NDM discovers disks

### ISSUE THREAD

**Issue by kmova** [openebs/openebs-docs#493]
As part of the default OpenEBS installation, there are some filters applied like OS disk, or based on the path name, etc. This is controlled via config file and should be documented.

**Comment by ranjithwingrider** [comment]
NDM is excluding following device path to avoid from creating cStor pools. This configuration is added under Configmap for node-disk-manager-config.

/dev/loop - loop devices.
/dev/fd - file descriptors.
/dev/sr - CD-ROM devices.
/dev/ram - ramdisks.
/dev/dm -lvm.
/dev/md -multiple device ( software RAID devices).

This has been added in documentation. Refer : https://docs.openebs.io/docs/next/faq.html#what-are-different-device-paths-excluded-by-ndm

**Comment by ranjithwingrider** [comment]
Any block disks available on the node (that can be listed with say lsblk) will be discovered by OpenEBS. Node Disk Manager(NDM) forms the DISK CRs in the following way

Scan the list of disks that are unmounted
Filter out the OS disks
Filter out any other disk patterns that are mentioned in openebs-operator.yaml.
NDM do some filters on the disks to exclude,for example boot disk. NDM is excluding following device path to avoid from creating cStor pools. This configuration is added in openebs-ndm-config under Configmap in openebs-operator.yaml. /dev/loop - loop devices. /dev/fd - file descriptors. /dev/sr - CD-ROM devices. /dev/ram - ramdisks. /dev/dm -lvm. /dev/md -multiple device ( software RAID devices).

It is also possible to customize by adding more disk types associated with your nodes. For example, used disks, unwanted disks and so on. Following is the default filters added in openebs-operator.yaml. This change must be done in the 'openebs-operator.yaml' file that you have downloaded before OpenEBS installation.

exclude: "loop,/dev/fd0,/dev/sr0,/dev/ram,/dev/dm-,/dev/md"

Example:

 filterconfigs:
   - key: path-filter
     name: path filter
     state: true
     include: ""
     exclude: "loop,/dev/fd0,/dev/sr0,/dev/ram,/dev/dm-,/dev/md"
This has been added in documentation. Refer : https://staging-docs.openebs.io/docs/next/faq.html#how-openebs-detects-disks-for-creating-cstor-pool
