### ISSUE TITLE
Need a troubleshooting guide for cStor Pools and volumes

### ISSUE THREAD

**Issue by kmova** [openebs/openebs-docs#494]
There a several questions being answered in the openebs slack related to configuration/setup of cStor Pools and Volumes. It will be great to have that information included into a Troubleshooting guide or tutorial in the OpenEBS documentation. 

The details are getting capture in : https://docs.google.com/document/d/1ly-PZ7S6Gm4rygNp7-NhcmBKFgSOjpAsa-KcJwjAao4/edit?usp=sharing

**Comment by ranjithwingrider** [comment]
There was an issue related to provisioning cStor volume raised by Aman in community channel
Below is the issue.
**----**
I was creating manual Cstor pool for disks attached to my nodes, but i am unable to claim volume using the custom storage pool cStor storage pools are running in healthy state.
```
gem-cstor-disk-9wzj-6c9c8f75c5-mq6gp                              2/2     Running   0          154m
gem-cstor-disk-iru2-68c85445cf-pqg6b                              2/2     Running   0          132m
gem-cstor-disk-m3bx-6fcddc7dcd-f9dg2                              2/2     Running   0          154m
```
From maya-apiserver,
```
2019/01/16 12:47:17.907038 [ERR] http: Request GET /latest/volumes/pvc-b8dacfcc-198c-11e9-9141-503eaa028845, error: error converting YAML to JSON: yaml: line 4: mapping values are not allowed in this context
2019/01/16 12:47:17.907070 [DEBUG] http: Request /latest/volumes/pvc-b8dacfcc-198c-11e9-9141-503eaa028845 (596.053376ms)
2019/01/16 12:47:43.536149 [DEBUG] http: Request /latest/volumes/pvc-b9a40023-198c-11e9-9141-503eaa028845 (GET)
I0116 12:47:43.536184       8 volume_endpoint_v1alpha1.go:52] cas template based volume request was received: method 'GET'
I0116 12:47:43.536206       8 volume_endpoint_v1alpha1.go:137] cas template based volume read request was received
E0116 12:47:44.705380       8 volume_endpoint_v1alpha1.go:175] failed to read cas template based volume: error 'error converting YAML to JSON: yaml: line 4: mapping values are not allowed in this context'
2019/01/16 12:47:44.705424 [ERR] http: Request GET /latest/volumes/pvc-b9a40023-198c-11e9-9141-503eaa028845, error: error converting YAML to JSON: yaml: line 4: mapping values are not allowed in this context
2019/01/16 12:47:44.705458 [DEBUG] http: Request /latest/volumes/pvc-b9a40023-198c-11e9-9141-5
```
**----**

**Comment by ranjithwingrider** [comment]
Above issue is arrived by a small space in StorageClass YAML. Once the space is corrected in StorageClass YAML, this problem is resolved.

**Comment by ranjithwingrider** [comment]
Added initial details of cStor debugging steps are provided in https://docs.openebs.io/docs/next/cstor.html#troubleshooting-areas. We will update more details in the same page only.
Sometime cStor related troubleshooting steps are added [here ](https://docs.openebs.io/docs/next/troubleshooting.html) also
