### ISSUE TITLE
Add performance benchmarking section

### ISSUE THREAD

**Issue by kmova** [openebs/openebs-docs#550]
Include steps to run performance benchmarking section, help to compare with different cStor tunables.

**Comment by ranjithwingrider** [comment]
It has been added in the documentation. Refer: https://docs.openebs.io/docs/next/performance.html
Here are the contents.

<h3>Steps for performance testing</h3>

**Setup cStorPool and StorageClass**

Choose the appropriate disks (SSDs or SAS or Cloud disks) and create pool and create StorageClass. For performance testing, performance numbers vary based 
* on the number of OpenEBS replicas (1 vs 3) (latency between cStor target and cStor replica)
* on whether all the replicas are in one zone or across multiple zones
* the network latency between the application pod and iSCSI target (cStor target)

**Run fio test through OpenEBS Litmus**
1. Clone litmus repository
   ```
   git clone https://github.com/openebs/litmus.git
   cd litmus/apps/fio/tests/performance
   ```
2. Edit run_litmus_test.yaml and modify the following
   ```
   - name: PROVIDER_STORAGE_CLASS
     value: openebs-standard
    #value: local-storage

   - name: APP_NODE_SELECTOR
     value: percona

   - name: FIO_TEST_PROFILE
     value: standard-ssd

   - name: FIO_SAMPLE_SIZE
     value: "128m"

   - name: FIO_TESTRUN_PERIOD
     value: "60"
   ```
3. Run the fio performance test
   ```
   kubectl create -f run_litmus_test.yaml
   ```
4. Observe the results at the end of the test

**Comment by ranjithwingrider** [comment]
Steps are documented under "Advanced Topics"
https://docs.openebs.io/docs/next/performance.html
