### ISSUE TITLE
Entire part of a subheading should be clickable

### ISSUE THREAD

**Issue by agarwalrounak** [openebs/openebs-docs#671]
In side navbar, the sub-headings under a heading are not entirely clickable. They can only be clicked when clicking on the text of the subheading. This should not be the case. 
![Screenshot from 2019-10-25 01-00-04](https://user-images.githubusercontent.com/38394281/67518690-e3f3ba00-f6c2-11e9-8b08-aff6b513a00e.png)
In the above image, the entire highlighted part should be clickable but only the text GitLab is clickable as of now. This creates a bad user experience because the text length varies for different sub-headings so different areas of different sub-headings are clickable and there is no uniformity. This should be fixed to make the entire highlighted part clickable.

**Comment by agarwalrounak** [comment]
Once this issue is approved, I will start working on it.

**Comment by sagarkrsd** [comment]
Good one @agarwalrounak. Please go ahead with the implementation.
