### ISSUE TITLE
Change the rating widget

### ISSUE THREAD

**Issue by ssaumya97** [openebs/openebs-docs#756]
The current rating option has a lot of reaction buttons. 
The ratings should be simpler.
A "was this helpful button?" should be a better option.

**Comment by kmova** [comment]
![image](https://user-images.githubusercontent.com/12488783/82357735-2431d580-9a23-11ea-808f-2be604a3eb6f.png)

A feedback widget based on google analytics has been added. 

Ref: https://github.com/openebs/openebs-docs/pull/769
