### ISSUE TITLE
Helm 3 can create namespace with install command

### ISSUE THREAD

**Issue by survivant** [openebs/openebs-docs#899]
in [https://docs.openebs.io/docs/next/installation.html#installation-through-helm](https://docs.openebs.io/docs/next/installation.html#installation-through-helm)   
for Helm 3, we can create the namespace with the install command.  Lot easier to understand and it need only one line.

````
helm install openebs openebs/openebs --create-namespace --namespace openebs
````

You can aolso specify the context with --kube-context=xyz  instead of switching context with kubectl

**Comment by survivant** [comment]
PS.  it works with Helm 3.2+  ( the current version is 3.4.1)

**Comment by survivant** [comment]
@kmova 
that page too talk about helm installation.  There is a line that is missing
kubectl create ns openebs     if you are not creating the namespace in the same time that installing openebs with helm

**Comment by kmova** [comment]
Update this as part of the 2.11. Please review the latest document on install. 
https://docs.openebs.io/docs/next/installation.html#installation-through-helm

Removed the references to helm 2 completely.
