### ISSUE TITLE
link to Prometheus redirect to a 404

### ISSUE THREAD

**Issue by survivant** [openebs/openebs-docs#915]
in the page : https://docs.openebs.io/docs/next/prometheus.html

the link : Live access to Prometheus dashboard    (which is : https://prometheuscstor.openebs.ci/    )

which return a 404.

**Comment by ranjithwingrider** [comment]
Hello @survivant . Thank you for notifying the error. We have updated the page with the latest Prometheus Operator deployment steps. https://docs.openebs.io/docs/next/prometheus.html.
